[package]
name = "bkes"
version = "0.1.0"
authors = ["Gerard Klijs <g.klijs@gmail.com>"]
edition = "2018"

[dependencies]

sled = "0.34"
prost = "0.7"
tokio = { version = "1.4", features = ["macros", "rt-multi-thread"] }
tonic = "0.4"

[build-dependencies]
tonic-build = "0.4"
